[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rov-software"
version = "0.0.1"
dependencies = [
  "smbus"
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT License"}