# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rov_messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12rov_messages.proto\x12\x03rov\"\xc7\x02\n\tHeartbeat\x12/\n\rsurface_error\x18\x01 \x01(\x0e\x32\x18.rov.Heartbeat.ErrorCode\x12\x17\n\x0f\x62\x61ttery_voltage\x18\x02 \x01(\x02\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12&\n\tthrusters\x18\x04 \x03(\x0b\x32\x13.rov.ThrusterStatus\x12$\n\tpdb_stati\x18\t \x03(\x0b\x32\x11.rov.PDBBusStatus\x12\x17\n\x0fpdb_temperature\x18\x05 \x01(\x02\x12\x11\n\ttimestamp\x18\x06 \x01(\x04\"a\n\tErrorCode\x12\x0c\n\x08NO_ERROR\x10\x00\x12\x1a\n\x16THRUSTER_COMMAND_ERROR\x10\x01\x12\x17\n\x13MOTOR_NOT_SPECIFIED\x10\x02\x12\x11\n\rVALUE_INVALID\x10\x03\"@\n\x0cPDBBusStatus\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0f\n\x07\x65nabled\x18\x03 \x01(\x08\x12\x13\n\x0b\x62us_current\x18\x02 \x01(\x02\"e\n\x0eThrusterStatus\x12\n\n\x02id\x18\x01 \x01(\r\x12\x10\n\x08velocity\x18\x02 \x01(\x02\x12\x0f\n\x07\x65nabled\x18\x03 \x01(\x08\x12\x0f\n\x07\x63urrent\x18\x04 \x01(\x02\x12\x13\n\x0btemperature\x18\x05 \x01(\x02\"\x95\x01\n\x0e\x43ontrolMessage\x12\x0b\n\x03run\x18\x01 \x01(\x08\x12\'\n\tthrusters\x18\x02 \x03(\x0b\x32\x14.rov.ThrusterCommand\x12\x11\n\tlights_on\x18\x03 \x01(\x08\x12\x12\n\ncamera_pan\x18\x04 \x01(\x02\x12\x13\n\x0b\x63\x61mera_tilt\x18\x05 \x01(\x02\x12\x11\n\ttimestamp\x18\x06 \x01(\x04\"-\n\x10HeartbeatRequest\x12\x19\n\x11request_heartbeat\x18\x01 \x01(\x08\"@\n\x0fThrusterCommand\x12\n\n\x02id\x18\x01 \x01(\r\x12\x10\n\x08velocity\x18\x02 \x01(\x02\x12\x0f\n\x07\x65nabled\x18\x03 \x01(\x08\"\xa6\x01\n\x0eNetworkMessage\x12-\n\x04type\x18\x01 \x01(\x0e\x32\x1f.rov.NetworkMessage.MessageType\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"T\n\x0bMessageType\x12\r\n\tHEARTBEAT\x10\x00\x12\x15\n\x11HEARTBEAT_REQUEST\x10\x01\x12\x0b\n\x07\x43ONTROL\x10\x02\x12\t\n\x05\x45RROR\x10\x03\x12\x07\n\x03\x41\x43K\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rov_messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEARTBEAT._serialized_start=28
  _HEARTBEAT._serialized_end=355
  _HEARTBEAT_ERRORCODE._serialized_start=258
  _HEARTBEAT_ERRORCODE._serialized_end=355
  _PDBBUSSTATUS._serialized_start=357
  _PDBBUSSTATUS._serialized_end=421
  _THRUSTERSTATUS._serialized_start=423
  _THRUSTERSTATUS._serialized_end=524
  _CONTROLMESSAGE._serialized_start=527
  _CONTROLMESSAGE._serialized_end=676
  _HEARTBEATREQUEST._serialized_start=678
  _HEARTBEATREQUEST._serialized_end=723
  _THRUSTERCOMMAND._serialized_start=725
  _THRUSTERCOMMAND._serialized_end=789
  _NETWORKMESSAGE._serialized_start=792
  _NETWORKMESSAGE._serialized_end=958
  _NETWORKMESSAGE_MESSAGETYPE._serialized_start=874
  _NETWORKMESSAGE_MESSAGETYPE._serialized_end=958
# @@protoc_insertion_point(module_scope)
